
package example.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConnectionsPort", targetNamespace = "build.soapserver.ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConnectionsPort {


    /**
     * 
     * @param registerConnectionRequest
     * @return
     *     returns example.ws.server.RegisterConnectionResponse
     */
    @WebMethod
    @WebResult(name = "registerConnectionResponse", targetNamespace = "build.soapserver.ws", partName = "registerConnectionResponse")
    public RegisterConnectionResponse registerConnection(
        @WebParam(name = "registerConnectionRequest", targetNamespace = "build.soapserver.ws", partName = "registerConnectionRequest")
        RegisterConnectionRequest registerConnectionRequest);

}
