
package example.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConnectionsPortService", targetNamespace = "build.soapserver.ws", wsdlLocation = "http://localhost:8080/soap/connections.wsdl?")
public class ConnectionsPortService
    extends Service
{

    private final static URL CONNECTIONSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONNECTIONSPORTSERVICE_EXCEPTION;
    private final static QName CONNECTIONSPORTSERVICE_QNAME = new QName("build.soapserver.ws", "ConnectionsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/connections.wsdl?");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONNECTIONSPORTSERVICE_WSDL_LOCATION = url;
        CONNECTIONSPORTSERVICE_EXCEPTION = e;
    }

    public ConnectionsPortService() {
        super(__getWsdlLocation(), CONNECTIONSPORTSERVICE_QNAME);
    }

    public ConnectionsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONNECTIONSPORTSERVICE_QNAME, features);
    }

    public ConnectionsPortService(URL wsdlLocation) {
        super(wsdlLocation, CONNECTIONSPORTSERVICE_QNAME);
    }

    public ConnectionsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONNECTIONSPORTSERVICE_QNAME, features);
    }

    public ConnectionsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConnectionsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConnectionsPort
     */
    @WebEndpoint(name = "ConnectionsPortSoap11")
    public ConnectionsPort getConnectionsPortSoap11() {
        return super.getPort(new QName("build.soapserver.ws", "ConnectionsPortSoap11"), ConnectionsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConnectionsPort
     */
    @WebEndpoint(name = "ConnectionsPortSoap11")
    public ConnectionsPort getConnectionsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("build.soapserver.ws", "ConnectionsPortSoap11"), ConnectionsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONNECTIONSPORTSERVICE_EXCEPTION!= null) {
            throw CONNECTIONSPORTSERVICE_EXCEPTION;
        }
        return CONNECTIONSPORTSERVICE_WSDL_LOCATION;
    }

}
